# -*- coding: utf-8 -*-
"""GPT_Text_Generation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VuqElc7VpgoCNRp67EpVHtFrlhR-Lcw9
"""

!pip install openai

!pip install pandas --upgrade

import pandas as pd
import json
import requests as rq
from io import BytesIO
from openai import OpenAI
import pickle

client = OpenAI(
   api_key="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",
)

# response = client.chat.completions.create(
#   model="gpt-3.5-turbo",
#   messages=[
#     {"role": "system", "content": "You are a helpful assistant."},
#     {"role": "user", "content": "Who won the world series in 2020?"},
#     {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
#     {"role": "user", "content": "Where was it played?"}
#   ]
# )

# f = open('arxivData.json', 'r')
# data = json.load(f)
# df = pd.json_normalize(data)

# df.head(10)

# df = df[['summary', 'title']]
# df = df[df['summary'].str.split().str.len() > 300]
# print(df['summary'].str.split().str.len().mean())

# len(df)

url1 = "https://github.com/Taichi22/CollegeCode/raw/main/CSE480/NIHMS1911044-supplement-1%20(2).xlsx"
data = rq.get(url1).content
df_1 = pd.read_excel(BytesIO(data), header=1)
df_1 = df_1.dropna()

df_1.head(10)

prompts_df = df_1[["ChatGPT Question with Title", "ChatGPT Question with Human-Derived Phrase"]]
title_prompts = prompts_df["ChatGPT Question with Title"].to_list()
phrase_prompts = prompts_df["ChatGPT Question with Human-Derived Phrase"].to_list()

responses = []
responses.append([])
responses.append([])
for i in range(len(title_prompts)):
  response = client.chat.completions.create(
  model="gpt-3.5-turbo",
  seed=42,
  messages=[
    {"role": "system", "content": "You are ChatGPT, a large language model trained by OpenAI, based on the GPT-3.5 architecture. Knowledge cutoff: 2022-01 Current date: 2023-12-03"},
    {"role": "user", "content": title_prompts[i]}
  ]
  )
  responses[0].append(response)
  responses[1].append(title_prompts[i])

cleaned_responses = [(responses[0][i].choices[0].message.content, title_prompts[i]) for i in range(len(title_prompts))]
with open(r'responses', 'w') as fp:
    fp.write("\n".join(str(item) for item in cleaned_responses))
import pickle
file = open("responses.pkl", "wb")
pickle.dump(cleaned_responses, file)
file.close()

import pickle
unpickle = pickle.load(open("responses.pkl", "rb"))

print(len(unpickle))

unpickle

import csv

with open('responses.csv', 'w', newline='') as file:
    # Step 4: Using csv.writer to write the list to the CSV file
    writer = csv.writer(file)
    writer.writerows(unpickle) # Use writerow for single list

import pandas as pd
df = pd.DataFrame(unpickle, columns=['value', 'prompt'])
df = df.to_csv('responses.csv', index=False)
pickle.dump(df, open("responses.pkl", "wb"))

